name: venv
channels:
  - conda-forge
  - cyclus
dependencies:
  - python=3.9
  - pip=22.2
  - jupyterlab=3.4.5
  - spacy-model-en_core_web_sm=3.3.0
  - java-jdk=8.25.17
  - pip:
    - scikit-learn==1.1.2
    - certifi==2022.6.15
    - joblib==1.1.0
    - numpy==1.23.2
    - scipy==1.9.0
    - threadpoolctl==3.1.0
    - pandas==1.4.3
    - nltk==3.7
    - commonregex==1.5.4
    - spacy==3.4.1
    - matplotlib==3.5.3
    - wasabi==0.9.1
    - Flask==2.2.2
    - pypmml==0.9.16